Executable = runPCSF.sh
Universe = vanilla

Notification = Never
Notify_user = drcronin@wisc.edu

Output = $ENV(outpath)/$(Cluster).$(Process).out
Error = $ENV(outpath)/$(Cluster).$(Process).err
Log = $ENV(outpath)/$(Cluster).$(Process).log

Rank = MachineOwner == "Virology"
Request_cpus = 1

Environment = "prizetype=$ENV(prizetype) conf=$ENV(conf) beta=$ENV(beta) mu=$ENV(mu) seed=$ENV(seed) outpath=$ENV(outpath) cluster=$(Cluster) process=$(Process) runningon=$$(Name)"


Queue
#END
